version: '2'
services:
  fdfs-tracker:
    image: suanmilk/fastdfs
    container_name: fdfs-tracker
    ports:
      - "22122:22122"
    restart: always
    privileged: true
    volumes:
      - ./fdfs-data/tracker:/fastdfs/tracker
    command: ["tracker"]
    networks:
      fdfs:
        ipv4_address: 172.64.0.100
  fdfs-storage:
    image: suanmilk/fastdfs
    container_name: fdfs-storage
    ports:
      - "23000:23000"
      - "8060:8888"
    restart: always
    privileged: true
    environment:
      - GROUP_NAME=group1
      - TRACKER_SERVER=fdfs-tracker:22122
      - GROUP_NAMES=group1
    volumes:
      - ./fdfs-data/storage:/fastdfs/storage
      - ./fdfs-data/storage_data:/fastdfs/storage_data
      - ./fdfs-data/storage/nginx/logs:/usr/local/nginx/logs
    networks:
      fdfs:
        ipv4_address: 172.64.0.101
    depends_on:
      - fdfs-tracker
    links:
      - fdfs-tracker
    command: ["storage"]
  fdfs-nginx:
    image: suanmilk/fastdfs
    container_name: fdfs-nginx
    ports:
      - "80:80"
    restart: always
    privileged: true
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./fdfs-data/nginx/logs:/usr/local/nginx/logs
      - ./fdfs-data/nginx:/fastdfs/nginx
    networks:
      fdfs:
        ipv4_address: 172.64.0.102
    command: ["nginx"]

networks:
  fdfs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.64.0.0/16
          gateway: 172.64.0.1
